platonakulov/project_hub/project_hub/urls.py
from django.contrib import admin
from django.urls import path
from portfolio import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('pf-home/', views.pf_home, name='pf-home'),
    path('pf-registration/', views.pf_registration, name='pf-registration'),
    path('pf-authorisation/', views.pf_authorisation, name='pf-authorisation'),
    path('pf-cart/', views.pf_cart, name='pf-cart'),
    path('pf-catalog/', views.pf_catalog, name='pf-catalog'),
    path('pf-profile/', views.pf_profile, name='pf-profile'),
    path('search-suggestions/', views.search_suggestions, name='search_suggestions'),
    path('add-to-cart/<slug:slug>/', views.add_to_cart, name='add-to-cart'),
    path('get-cart/', views.get_cart, name='get-cart'),
    path('fuels/<slug:slug>/', views.fuel_detail, name='fuel-detail'),
    path('eg-home/', views.eg_home, name='eg-home'),
    path('foa-home/', views.foa_home, name='foa-home'),
    path('foa-en-home/', views.foa_en_home, name='foa-en-home'),
    path('get-fuel-url/', views.get_fuel_url, name='get_fuel_url'),

]

handler404 = 'portfolio.views.error_404'

platonakulov/project_hub/portfolio/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.utils.crypto import get_random_string

class Fuel(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo_url = models.URLField(blank=True)
    slug = models.SlugField(max_length=12, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)

    def generate_unique_slug(self):
        random_slug = get_random_string(length=12)
        return random_slug

    def __str__(self):
        return self.name



class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fuel_slug = models.SlugField(max_length=12)  # Ссылка на уникальный URL топлива

    def __str__(self):
        return f"{self.user.username}'s Cart Item - {self.fuel_slug}"

class Review(models.Model):
    name = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

platonakulov/project_hub/templates/fuel_detail.html
{% extends 'pf_base.html' %}
{% load static %}

{% block content %}
<div class="content-container row">
    <div class="product-image col-6">
        <h2 class="product-name">{{ fuel.name }}</h2>
        <img src="{{ fuel.photo_url }}" alt="{{ fuel.name }}">
    </div>
    <div class="product-info col-5 d-flex flex-column">
        <div class="d-flex justify-content-end mb-3">
            <p class="product-price">{{ fuel.price|floatformat:0 }} ₽</p>
            <button class="add-to">Добавить в корзину</button>
        </div>
        <div>
            <p class="product-description">Описание товара: {{ fuel.description }}</p>
        </div>
    </div>
</div>
{% endblock %}

platonakulov/project_hub/templates/home.html
{% load static %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Главная</title>
<link rel="shortcut icon" href="favicon.png" type="image/x-icon">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>

    <button onclick="scrollToTop()" id="scrollBtn" title="Вверх"><i class="bi bi-arrow-up-short"></i></button>
    <nav class="navbar navbar-expand-lg sticky-top py-3">
        <div class="d-flex mx-auto">
          <a class="navbar-brand my-auto" href="#">Платон Акулов</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <form class="d-flex my-auto" role="search">
                <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
            </form>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item" style="margin-left: 50px;">
                  <a class="nav-link" href="#">Главная</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#about_me">Обо мне</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="#contact">Контакты</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <main>
        <video autoplay muted loop id="video-background">
            <source src="{% static 'img/video.mp4' %}" type="video/mp4">
        </video>
        <div class="container">
            <button class="pause-button" id="toggleButton"><i id="icon" class="bi bi-pause"></i></button>
            <div class="row">
                <div class="col-12">
                    <h4 class="title my-5">Мои Проекты</h4>
                </div>
              <div class="col-md-6">
                <a href="{% url 'pf-home' %}" class="card">
                  <div class="card-body">
                    <h1>Power Fuel</h1>
                    <p>Сайт по спортпиту</p>
                  </div>
                </a>
              </div>
              <div class="col-md-6">
                <a href="{% url 'eg-home' %}" class="card">
                  <div class="card-body">
                    <h1>Easy Goal</h1>
                    <p>Тасктреккер</p>
                  </div>
                </a>
              </div>
              <div class="col-md-6">
                <a href="{% url 'foa-home' %}" class="card">
                  <div class="card-body">
                    <h1>Smart Skills</h1>
                    <p>Сайт по курсам</p>
                  </div>
                </a>
              </div>
              <div class="col-md-6">
                <a href="{% url 'foa-home' %}" class="card">
                  <div class="card-body">
                    <h1>Fears Of Alone</h1>
                    <p>Сайт о серии хоррор играх</p>
                  </div>
                </a>
              </div>
              <div class="col-md-6">
                <a href="#" class="card">
                  <div class="card-body">
                    <h1>Donut Dawg</h1>
                    <p>Пончиковая</p>
                  </div>
                </a>
              </div>
              <div class="col-md-6">
                <a href="#" class="card">
                  <div class="card-body">
                    <h1>SmallDickBigDreams</h1>
                    <p>Веб-блог</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
      </main>
      <about>
        <div class="container">
          <h4 class="title my-5" id="about_me">Обо мне</h4>
          <p>
            Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Что ты знаешь обо мне?
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
Ты ничего не знаешь обо мне
          </p>
        </div>
        <h4 class="title my-5" id="contact">Контакты</h4>
        
      </about>
      <footer class="footer">
        <div class="container">
            <div class="footer-content mx-auto">
                <div class="contact-info">
                    <p>Акулов П. А.</p>
                    <p>Email: <a href="mailto:platonakulov@outlook.com">platonakulov@outlook.com</a></p>
                    <p>Phone: <a href="tel:+79001191820">+7 (900) 119-18-20</a></p>
                </div>
                <div class="social-links">
                    <h6>Связаться со мной</h6>
                    <a href="https://t.me/tombeckles" target="_blank">
                      <img src="{% static "img/tg.png" %}" alt="VK" style="width: 35px; height: 35px;">
                    </a>
                    <a href="https://api.whatsapp.com/send?phone=79001191820&text=Разрабатываю%20сайты%20разной%20степени%20сложности" target="_blank">
                      <img src="{% static "img/wa.png" %}" alt="VK" style="width: 35px; height: 35px;">
                    </a>
                    <a href="https://vk.com/tommyhellaniggets" target="_blank">
                      <img src="{% static "img/vk.png" %}" alt="VK" style="width: 35px; height: 35px;">
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <script>
      document.addEventListener("DOMContentLoaded", function() {
          var video = document.getElementById("video-background");
          var button = document.getElementById("toggleButton");
          var icon = document.getElementById("icon");
      
          button.addEventListener("click", function() {
              if (video.paused) {
                  video.play();
                  icon.className = "bi bi-pause";
              } else {
                  video.pause();
                  icon.className = "bi bi-play";
              }
          });
      });
      
    </script>
    <script>
        window.onscroll = function() {scrollFunction()};
    
    function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("scrollBtn").style.display = "block";
        } else {
            document.getElementById("scrollBtn").style.display = "none";
        }
    }
    
    function scrollToTop() {
        document.body.scrollTop = 0; // Для Safari
        document.documentElement.scrollTop = 0; // Для Chrome, Firefox, IE и Opera
    }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

platonakulov/project_hub/templates/pf_404.html
{% extends 'pf_base.html' %}
{% load static %}

{% block title %}
    Страница не найдена
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h1>404</h1>
                <h2>Страница не найдена</h2>
                <p>Извините, запрашиваемая страница не существует.</p>
                <a href="{% url 'pf-home' %}" class="btn btn-primary">Вернуться на главную</a>
            </div>
        </div>
    </div>
{% endblock %}

platonakulov/project_hub/templates/pf_authorisation.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Войти</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Poppins&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Подключение пользовательских стилей -->
    <link href="{%static 'register-auth.css'%}" rel="stylesheet">
</head>
<body>

{% block content %}
    <div class="container-fluid contimg">
        <div class="container d-flex align-items-center justify-content-center vh-100">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-start align-items-center mb-3">
                        <a href="{% url 'home' %}"><i class="bi bi-arrow-left-short"></i></a>
                        <a href="{% url 'registration' %}" class="auth-link ms-auto" style="text-decoration: none;">Регистрация</a>
                    </div>
                    <h5 class="card-title text-center mb-4">Авторизация</h5>
                    <form method="post" action="{% url 'authorisation' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="email" class="form-label visually-hidden">Email</label>
                            <div class="input-group">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label visually-hidden">Пароль</label>
                            <div class="input-group">
                                <input type="password" class="form-control" id="password" name="password" placeholder="Пароль" required>
                            </div>
                        </div>
                        <!-- Указание наличия ошибки -->
                        {% if error_message %}
                        <div class="alert alert-danger" role="alert">
                            {{ error_message }}
                        </div>
                        {% endif %}
                        <div class="d-flex submit">
                            <button type="submit" class="btn btncolor" id="loginBtn">Войти</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

platonakulov/project_hub/templates/pf_cart.html
{% extends 'pf_base.html' %}

{% block title %}
    Корзина - Power Fuel
{% endblock %}

{% block content %}
    <h1>Корзина</h1>

    {% if cart_items %}
        <ul>
            {% for item in cart_items %}
                <li>
                    {{ item.fuel.name }} - {{ item.quantity }} шт. - {{ item.total_price }} ₽
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Ваша корзина пуста</p>
    {% endif %}
{% endblock %}

platonakulov/project_hub/templates/pf_catalog.html
{% extends 'pf_base.html' %}
{% load static %}

{% block title %}
    Каталог
{% endblock %}
{% block content %}
<div class="cards-container" id="cardsContainer">
    {% for fuel in fuels %}
    <form action="{% url 'add-to-cart' slug=fuel.slug %}" method="post">
        {% csrf_token %}
        <div class="card-item">
            <a href="{% url 'fuel-detail' slug=fuel.slug %}">
                <div class="card-image-item">
                    <img src="{{ fuel.photo_url }}" alt="{{ fuel.name }}">
                </div>
            </a>
            <div class="card-details">
                <p class="card-price">{{ fuel.price|floatformat:0 }} ₽</p>
                <p class="card-title">{{ fuel.name }}</p>
                <button type="submit" class="btn-cart">В корзину</button>
            </div>
        </div>
    </form>
    {% endfor %}
</div>



{% if fuels.has_other_pages %}
<nav aria-label="Пример навигации по страницам">
  <ul class="pagination">
    {% if fuels.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ fuels.previous_page_number }}" aria-label="Предыдущая">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% for i in fuels.paginator.page_range %}
    <li class="page-item {% if fuels.number == i %}active{% endif %}">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endfor %}
    {% if fuels.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ fuels.next_page_number }}" aria-label="Следующая">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}

<script>
    document.querySelectorAll('.btn-cart').forEach(btn => {
        btn.addEventListener('click', function(event) {
            event.preventDefault(); // Отменяем стандартное действие кнопки

            const form = this.closest('form'); // Находим ближайшую форму
            const formData = new FormData(form); // Создаем объект FormData для данных формы

            fetch(form.action, { // Отправляем POST-запрос на сервер
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}', // Передаем CSRF-токен
                }
            }).then(response => {
                if (response.ok) {
                    // Обновляем содержимое корзины на странице
                    updateCartContent();
                    alert('Товар добавлен в корзину!');
                } else {
                    alert('Ошибка при добавлении товара в корзину.');
                }
            }).catch(error => {
                console.error('Ошибка:', error);
            });
        });
    });

    function updateCartContent() {
        // Получаем контейнер корзины
        const cart = document.getElementById('cart');

        // Очищаем содержимое корзины
        cart.innerHTML = '';

        // Добавляем заголовок и кнопку закрытия
        const cartContent = document.createElement('div');
        cartContent.classList.add('cart-content');
        const cartTitle = document.createElement('h2');
        cartTitle.textContent = 'Корзина';
        const closeBtn = document.createElement('div');
        closeBtn.classList.add('close-btn');
        closeBtn.textContent = 'Закрыть';
        closeBtn.addEventListener('click', closeCart);
        cartContent.appendChild(cartTitle);
        cartContent.appendChild(closeBtn);
        cart.appendChild(cartContent);

        // Получаем данные о корзине из сессии
        fetch('/get-cart/')  // Предполагается, что есть URL для получения содержимого корзины
            .then(response => response.json())
            .then(data => {
                // Если корзина не пуста, добавляем содержимое
                if (Object.keys(data.cart).length > 0) {
                    for (const [slug, item] of Object.entries(data.cart)) {
                        const cartItemHTML = `
                            <div class="cart-item">
                                <img src="${item.photo_url}" alt="${item.name}">
                                <p>${item.name}</p>
                                <p>${item.price} ₽</p>
                            </div>`;
                        cartContent.innerHTML += cartItemHTML;
                    }
                } else {
                    // Если корзина пуста, добавляем соответствующее сообщение
                    const emptyCartMsg = document.createElement('p');
                    emptyCartMsg.textContent = 'Корзина пуста.';
                    cartContent.appendChild(emptyCartMsg);
                }
            })
            .catch(error => {
                console.error('Ошибка получения содержимого корзины:', error);
            });
    }

    function closeCart() {
        // Скрытие корзины при закрытии
        const cart = document.getElementById('cart');
        cart.style.display = 'none';
    }
</script>



<script src="{% static 'js/search_scripts.js' %}"></script>

platonakulov/project_hub/templates/pf_home.html
{% extends 'pf_base.html' %}
{% load static %}

{% block title %}
    Главная - Power Fuel
{% endblock %}

{% block profile_link %}
    {% if user.is_authenticated %}
        Профиль
    {% else %}
        Войти
    {% endif %}
{% endblock %}

{% block profile_dropdown %}
    {% if user.is_authenticated %}
        <li><a class="dropdown-item" href="{% url 'pf-profile' %}">Личный кабинет</a></li>
        <div class="dropdown-divider"></div> 
        <li><a class="dropdown-item" href="{% url 'pf-cart' %}">Корзина</a></li>
    {% else %}
        <li><a class="dropdown-item" href="{% url 'pf-authorisation' %}">Войти</a></li>
        <li><a class="dropdown-item" href="{% url 'pf-registration' %}">Регистрация</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner pt-3" style="border-radius: 15px; height: 500px">
        <div class="carousel-item active">
            <img src="{% static 'img/carusel3.jpg' %}" class="d-block w-100" alt="..." style="border-radius: 15px">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/carusel1.jpg' %}" class="d-block w-100" alt="..." style="border-radius: 15px">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/carusel2.jpg' %}" class="d-block w-100" alt="..." style="border-radius: 15px">
        </div>
        </div>
    </div>
    <p class="zaglav" id="catalog" style="background-color: var(--color-gray);">- Каталог -</p>
    <div class="cards-container" id="cardsContainer">
        {% for fuel in fuels %}
        <a href="{% url 'fuel-detail' slug=fuel.slug %}">
            <div class="card-item">
                <div class="card-image-item">
                    <img src="{{ fuel.photo_url }}" alt="{{ fuel.name }}">
                </div>
                <div class="card-details">
                    <p class="card-price">{{ fuel.price|floatformat:0 }} ₽</p>
                    <p class="card-title">{{ fuel.name }}</p>
                    <button type="submit" class="btn-cart col-12">В корзину</button>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    
    <div class="container con-bg mt-3">
        <p class="zaglav" id="about" style="background-color: var(--color-gray);">- Отзывы -</p>
        <div class="row">
            {% for review in reviews %}
            <div class="col-md-4 review">
                <div class="card" style="background-color: var(--color-gray); border-radius: 10px;  border: none;">
                    <div class="card-body" style="background-color: var(--color-gray); border-radius: 10px; border: none;">
                        <p class="review-name text-center">{{ review.name }}</p>
                        <p class="text-center">{{ review.content }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <p>Пока нет отзывов.</p>
            {% endfor %}
        </div>
        <p>
          <button class="btn btn-add-comment d-flex mx-auto" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Добавить комментарий
          </button>
        </p>
        <div class="collapse" id="collapseExample">
          <div class="card card-body" style="height: 300px; border-radius: 15px; background-color: var(--color-gray)">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_name" class="form-label">Имя</label>
                    <input type="text" class="form-control" id="id_name" name="name">
                </div>
                <div class="mb-3">
                    <label for="id_content" class="form-label">Отзыв</label>
                    <textarea class="form-control" id="id_content" name="content" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary d-flex mx-auto">Добавить отзыв</button>
            </form>
          </div>
        </div>
    </div>

    </div>
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>

platonakulov/project_hub/templates/pf_profile.html
{% extends 'pf_base.html' %}

{% block title %}
    Профиль - Power Fuel
{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col-md-6 offset-md-3">
        <h2 class="text-center mb-4">Профиль пользователя</h2>
        <p><strong>Имя пользователя:</strong> {{ user.username }}</p>
        <p><strong>Эл. почта:</strong> {{ user.email }}</p>

        <h3 class="mt-4">Сменить пароль</h3>
        <form method="post">
            {% csrf_token %}
            {{ password_change_form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить пароль</button>
        </form>

        <h3 class="mt-4">Сменить электронную почту</h3>
        <form method="post">
            {% csrf_token %}
            {{ user_change_form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить эл. почту</button>
        </form>

        <h3 class="mt-4">Другие действия</h3>
        <a href="{% url 'pf_logout' %}" class="btn btn-danger">Выйти</a>
        <a href="{% url 'pf_login' %}" class="btn btn-secondary">Сменить пользователя</a>
    </div>
</div>
{% endblock %}